name: Gerar VOD Automatico
on:
  push:
    paths:
      - 'automacao_vod/links_brutos.txt' # Ajustado para o nome real do seu arquivo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - name: Rodar Processador
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python automacao_vod/processador.py
      - name: Commit e Push
        run: |
          git config --global user.name "Bot VOD"
          git config --global user.email "bot@vod.com"
          git add lista_final_vod.m3u
          git commit -m "Lista atualizada automaticamente" || exit 0
          git push

