name: Atualizar Lista VOD com TMDb

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar Dependências
      run: pip install requests

    - name: Executar Processador
      run: python processador.py
      env:
        # Recomendo salvar sua chave nos 'Secrets' do GitHub como TMDB_KEY
        TMDB_API_KEY: ${{ secrets.TMDB_KEY }} 

    - name: Salvar alterações
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add lista_final_vod.m3u
        git commit -m "Auto-update: Lista com Posters TMDb" || exit 0
        git push
