name: 🎬 Automação VOD e TV ao Vivo

on:
  push:
    paths:
      - 'automacao_vod/links_*.txt'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 📦 Instalar Dependências
        run: pip install requests

      - name: 🎬 Rodar Processador
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python automacao_vod/processador.py

      - name: 💾 Commit e Push
        run: |
          git config --global user.name "VOD Bot"
          git config --global user.email "vod-bot@users.noreply.github.com"
          git add automacao_vod/lista_final_vod.m3u
          if ! git diff --cached --quiet; then
            git commit -m "🔄 [AUTO] Lista Final Atualizada"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
